In [5]:
from recommendation import get_data
data = get_data(category=True, city=True, prefecture=True)

In [6]:
data

HeteroData(
  (city, cityadj, city)=[2, 8445],
  spot={
    train_mask=[42852],
    valid_mask=[42852],
    test_mask=[42852],
    y=[42852],
    x=[42852, 512]
  },
  word={ x=[68340, 600] },
  category={ x=[290, 290] },
  city={
    x=[1709, 12],
    y=[1709],
    train_mask=[1709],
    valid_mask=[1709],
    test_mask=[1709]
  },
  pref={
    x=[47, 32],
    y=[47],
    train_mask=[47],
    valid_mask=[47],
    test_mask=[47]
  },
  user={
    x=[28251, 128],
    user_pos=[2146716],
    user_neg=[2146716],
    item_pos=[2146716],
    item_neg=[2146716]
  },
  (spot, relate, word)={ edge_index=[2, 642780] },
  (word, revrelate, spot)={ edge_index=[2, 642780] },
  (spot, has, category)={ edge_index=[2, 94658] },
  (category, revhas, spot)={ edge_index=[2, 94658] },
  (spot, belongs, city)={ edge_index=[2, 42852] },
  (city, revbelong, spot)={ edge_index=[2, 42852] },
  (pref, prefadj, pref)={ edge_index=[2, 172] },
  (city, belong, pref)={ edge_index=[2, 1991] },
  (pref, rebelong, ci

In [26]:
a = [torch.rand(2,3), torch.rand(2,3), torch.rand(2,3)]
print(a)
torch.stack(a, dim=1).size()
torch.mean(torch.stack(a, dim=1), dim=1)

[tensor([[0.2804, 0.7629, 0.5385],
        [0.6592, 0.8089, 0.4567]]), tensor([[0.6985, 0.2272, 0.7313],
        [0.3959, 0.5283, 0.0289]]), tensor([[0.4874, 0.2388, 0.7617],
        [0.7477, 0.3847, 0.7999]])]


tensor([[0.4888, 0.4096, 0.6771],
        [0.6009, 0.5740, 0.4285]])

In [12]:
df = pd.read_csv('/home/yamanishi/project/trip_recommend/model/recommendation/result/result.csv')
df.head()

recall  accuracy  best_epoch model_type  num_layers     lr  \
0  0.00172    0.0021           0        hgt           5  0.002   

   hidden_channels  concat  loss_city_weight  loss_category_weight  \
0               64   False                 0                     0   

   city_pop_weight  spot_pop_weight  data_word  data_category  data_city  \
0                0                0       True           True       True   

   data_prefecture  Unnamed: 16  
0             True     -0.74926

In [1]:
torch.cat(a, dim=1).size()

NameError: name 'a' is not defined

In [14]:
from torch_geometric.nn.conv import HANConv, HGTConv
conv = HANConv(in_channels=-1, out_channels=128, metadata=data.metadata())
conv = HGTConv(in_channels=-1, out_channels=128, metadata=data.metadata(), heads=4, group='mean')

In [15]:
device = 'cuda:0'
data.to(device)
conv.to(device)
conv(data.x_dict, data.edge_index_dict)

{'spot': tensor([[-0.0288, -0.0596,  0.0634,  ...,  0.0194,  0.0320,  0.0303],
         [-0.0655, -0.0652,  0.0009,  ...,  0.0245,  0.0261,  0.0752],
         [ 0.0032, -0.0506,  0.0455,  ..., -0.0364, -0.0711,  0.0404],
         ...,
         [-0.0679, -0.0551,  0.0629,  ..., -0.0462,  0.0336,  0.0534],
         [-0.0356, -0.0256,  0.0379,  ..., -0.0378,  0.0169,  0.0432],
         [-0.0527, -0.0557,  0.0059,  ..., -0.0278,  0.0228, -0.0088]],
        device='cuda:0', grad_fn=<AddmmBackward0>),
 'word': tensor([[-1.9727e-01,  9.5084e-04, -3.6135e-03,  ...,  8.4128e-03,
           1.4423e-01,  1.6481e-01],
         [-4.8239e-01,  3.6992e-01, -1.3637e-01,  ..., -4.3266e-01,
           5.1114e-01,  4.1980e-01],
         [-6.1266e-02,  2.3281e-01,  2.4414e-01,  ..., -1.4070e-01,
           2.7913e-01,  2.4021e-01],
         ...,
         [-1.5504e-01,  1.2582e-01,  3.5365e-02,  ...,  3.5207e-02,
           1.3466e-01,  9.7789e-02],
         [-3.3779e-01,  1.4885e-01,  3.5253e-04,  ..., -1

In [1]:
str(True)

'True'

In [4]:
data

HeteroData(
  spot={
    train_mask=[42852],
    valid_mask=[42852],
    test_mask=[42852],
    y=[42852],
    x=[42852, 512]
  },
  word={ x=[68340, 600] },
  user={
    x=[28251, 128],
    user_pos=[2146716],
    user_neg=[2146716],
    item_pos=[2146716],
    item_neg=[2146716]
  },
  (spot, relate, word)={ edge_index=[2, 642780] },
  (word, revrelate, spot)={ edge_index=[2, 642780] },
  (user, visit, spot)={ edge_index=[2, 2146716] },
  (spot, revvisit, user)={ edge_index=[2, 2146716] }
)

In [5]:
from torch_geometric.nn import HeteroLinear
linear = HeteroLinear(-1, 128, len(data.x_dict.keys()))
linear(data.x_dict)

TypeError: forward() missing 1 required positional argument: 'type_vec'

In [1]:
import torch.nn as nn
encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8)
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)
src = torch.rand(10, 32, 512)
out = transformer_encoder(src)

In [3]:
transformer_encoder(torch.rand(500,5,512))

tensor([[[ 1.6938, -0.4604,  1.3951,  ..., -0.4941, -0.1565,  0.1207],
         [-0.3422, -0.8063,  1.7492,  ..., -1.3343,  0.0558, -0.4790],
         [-0.4813, -0.8356,  1.6242,  ..., -1.1597, -0.1464,  0.4727],
         [-1.4184, -0.7773,  1.1830,  ..., -0.4891, -0.2813,  0.2164],
         [ 0.0397, -1.0320,  2.3576,  ..., -0.6497, -0.9610, -0.2784]],

        [[ 0.4420, -0.3877,  1.7163,  ..., -0.1106, -0.7346,  0.9244],
         [-0.1781, -0.4102,  1.5294,  ...,  0.1275,  0.0566,  0.1262],
         [-0.6370,  0.1568,  1.3207,  ..., -0.6263,  0.0112,  0.0030],
         [-0.0536, -0.5924,  0.6969,  ...,  0.0097,  0.2753,  0.1213],
         [ 0.1633, -0.7276,  0.8970,  ..., -1.2248,  0.3632,  0.3481]],

        [[ 0.3711, -1.0998,  0.9549,  ..., -1.2546, -0.4199, -0.5805],
         [-0.1377, -0.2571,  2.1186,  ..., -1.5979,  0.2015,  0.6335],
         [-0.5531, -0.0821,  1.8383,  ..., -0.7377, -0.6298, -0.5093],
         [-0.7340, -0.2288,  1.8524,  ..., -1.0687,  0.0162, -0.3630],
  

In [1]:
import os
 
isempty = os.stat('/home/yamanishi/project/trip_recommend/model/recommendation/result.csv').st_size == 0
print(isempty)

True


In [3]:
a = 0.224151533535
round(a,5)

0.22415

In [4]:
a=np.array(['a','b','c'])
with open('log.txt', 'w') as f:
    f.write('train','max', a.)

TypeError: write() takes exactly one argument (3 given)

In [8]:
import torch.nn as nn
gru = nn.GRUCell(128,128)

In [10]:
gru(torch.rand(512,128), torch.rand(512,128)).shape

torch.Size([512, 128])

In [3]:
a = torch.rand(3,2)
print(a)
print(a.norm(2))
a.norm(2).pow(2)

tensor([[0.0282, 0.8086],
        [0.4328, 0.8383],
        [0.5413, 0.9000]])
tensor(1.6272)


tensor(2.6476)

In [2]:
import os
jalan_dir = '/home/yamanishi/project/trip_recommend/data/jalan/graph'
spot_x = torch.from_numpy(np.load('/home/yamanishi/project/trip_recommend/data/jalan/graph/spot_img_emb_multi_ResNet.npy'))

In [3]:
spot_x = torch.mean(spot_x.reshape(-1, 5, 512), dim=1)

In [4]:
spot_x.shape

torch.Size([42852, 512])

In [5]:
torch.mean(spot_x)

tensor(0.7121)

In [6]:
spot_x[0]

tensor([0.8861, 0.1727, 0.3560, 0.4237, 0.9756, 0.2811, 0.5997, 2.6993, 0.3634,
        0.2504, 0.3406, 0.2082, 0.1303, 0.6664, 0.3183, 0.2861, 0.3436, 0.9166,
        0.5570, 0.3240, 0.6952, 0.5925, 0.4534, 0.4229, 1.0731, 0.7393, 0.1310,
        1.5734, 0.4849, 0.1031, 0.2981, 0.4329, 0.4725, 0.3331, 0.1426, 0.2316,
        0.0379, 0.2409, 0.2281, 0.5225, 0.2656, 0.2760, 0.3464, 1.2909, 0.3082,
        0.1257, 0.2667, 0.0742, 0.6775, 0.7610, 0.4204, 0.3792, 0.5434, 0.3709,
        1.1557, 0.4075, 3.4529, 0.1250, 0.3780, 0.4171, 0.2116, 0.1498, 1.2724,
        0.1236, 0.5222, 1.1156, 0.1279, 0.3733, 0.7053, 0.5600, 0.3822, 0.1494,
        0.6044, 0.4425, 0.2629, 0.1354, 0.2727, 0.6583, 0.1713, 0.4862, 0.0106,
        0.6679, 0.4752, 0.7715, 0.2611, 0.6974, 0.2824, 0.5563, 0.2974, 0.6160,
        0.5564, 0.3807, 0.3273, 0.1836, 0.3606, 0.3206, 0.5458, 0.8120, 0.2231,
        0.4008, 0.0208, 1.1539, 0.5960, 0.1766, 2.9566, 0.5906, 0.4219, 0.4640,
        0.3433, 0.6275, 0.3723, 0.2794, 

In [10]:
a = torch.rand(5,3)
torch.nn.init.normal_(a,0, 0.1)
a

tensor([[ 0.0856, -0.0886,  0.1073],
        [ 0.0795,  0.0068,  0.0853],
        [-0.1042, -0.0900, -0.0025],
        [-0.0044,  0.1520,  0.0773],
        [ 0.0649,  0.0260,  0.0695]])

In [4]:
df = pd.read_csv('/home/yamanishi/project/trip_recommend/model/popularity/result/result.csv', names=['cor', 'best_epoch', 'model_type', 'num_layers','lr','hidden_channels', 'concat', 
                        'city_pop_weight','data_word' , 'data_category', 'data_city', 'data_pref'])

In [5]:
df.head()

cor  best_epoch model_type  num_layers      lr  hidden_channels  \
0  0.79733         339       ggnn           4  0.0001              320   
1  0.76015         649       sage           2  0.0001              128   
2  0.80031         359       ggnn           4  0.0001              320   
3  0.78286         319       ggnn           2  0.0001              128   
4  0.78397         569     ggnnv2           2  0.0001              128   

   concat  city_pop_weight  data_word  data_category  data_city  data_pref  
0   False                0       True           True       True       True  
1   False                0       True           True       True       True  
2   False                0       True           True       True       True  
3   False                0       True           True       True       True  
4   False                0       True           True       True       True

In [7]:
df[df['model_type']=='hgt']

cor  best_epoch model_type  num_layers      lr  hidden_channels  \
6   0.76224         299        hgt           2  0.0001              128   
13  0.77095         209        hgt           2  0.0001              256   
20  0.75981         189        hgt           2  0.0001              384   
28  0.76689         259        hgt           3  0.0001              128   
35  0.76390         259        hgt           3  0.0001              256   
43  0.77383         199        hgt           3  0.0001              384   
50  0.76744         329        hgt           4  0.0001              128   
57  0.77089         259        hgt           4  0.0001              256   
65  0.76994         179        hgt           4  0.0001              384   
72  0.76266         339        hgt           5  0.0001              128   
78  0.77399         279        hgt           5  0.0001              256   

    concat  city_pop_weight  data_word  data_category  data_city  data_pref  
6    False                0       True           True       True       True  
13   False                0       True           True       True       True  
20   False                0       True           True       True       True  
28   False                0       True           True       True       True  
35   False                0       True           True       True       True  
43   False                0       True           True       True       True  
50   False                0       True           True       True       True  
57   False                0       True           True       True       True  
65   False                0       True           True       True       True  
72   False                0       True           True       True       True  
78   False                0       True           True       True       True

In [9]:
df[df['model_type']=='sage']

cor  best_epoch model_type  num_layers      lr  hidden_channels  \
1   0.76015         649       sage           2  0.0001              128   
9   0.74957         349       sage           2  0.0001              256   
16  0.75552         359       sage           2  0.0001              384   
25  0.77734         659       sage           3  0.0001              128   
32  0.77156         349       sage           3  0.0001              256   
38  0.77036         359       sage           3  0.0001              384   
47  0.77505         539       sage           4  0.0001              128   
53  0.78030         329       sage           4  0.0001              256   
60  0.78058         279       sage           4  0.0001              384   
69  0.78649         609       sage           5  0.0001              128   
75  0.78561         359       sage           5  0.0001              256   
81  0.79016         309       sage           5  0.0001              384   

    concat  city_pop_weight  data_word  data_category  data_city  data_pref  
1    False                0       True           True       True       True  
9    False                0       True           True       True       True  
16   False                0       True           True       True       True  
25   False                0       True           True       True       True  
32   False                0       True           True       True       True  
38   False                0       True           True       True       True  
47   False                0       True           True       True       True  
53   False                0       True           True       True       True  
60   False                0       True           True       True       True  
69   False                0       True           True       True       True  
75   False                0       True           True       True       True  
81   False                0       True           True       True       True

In [10]:
df[df['model_type']=='ggnn']

cor  best_epoch model_type  num_layers      lr  hidden_channels  \
0   0.79733         339       ggnn           4  0.0001              320   
2   0.80031         359       ggnn           4  0.0001              320   
3   0.78286         319       ggnn           2  0.0001              128   
11  0.78498         279       ggnn           2  0.0001              256   
19  0.79322         229       ggnn           2  0.0001              384   
26  0.78873         479       ggnn           3  0.0001              128   
33  0.78993         309       ggnn           3  0.0001              256   
40  0.79776         249       ggnn           3  0.0001              384   
48  0.79622         659       ggnn           4  0.0001              128   
55  0.79327         359       ggnn           4  0.0001              256   
61  0.80076         289       ggnn           4  0.0001              384   
71  0.79438         669       ggnn           5  0.0001              128   
76  0.80337         509       ggnn           5  0.0001              256   
83  0.80010         459       ggnn           5  0.0001              384   

    concat  city_pop_weight  data_word  data_category  data_city  data_pref  
0    False                0       True           True       True       True  
2    False                0       True           True       True       True  
3    False                0       True           True       True       True  
11   False                0       True           True       True       True  
19   False                0       True           True       True       True  
26   False                0       True           True       True       True  
33   False                0       True           True       True       True  
40   False                0       True           True       True       True  
48   False                0       True           True       True       True  
55   False                0       True           True       True       True  
61   False                0       True           True       True       True  
71   False                0       True           True       True       True  
76   False                0       True           True       True       True  
83   False                0       True           True       True       True

In [11]:
df[df['model_type']=='ggnnv4']

cor  best_epoch model_type  num_layers      lr  hidden_channels  \
8   0.79070         499     ggnnv4           2  0.0001              128   
14  0.79130         299     ggnnv4           2  0.0001              256   
21  0.79566         259     ggnnv4           2  0.0001              384   
27  0.79074         649     ggnnv4           3  0.0001              128   
34  0.79759         529     ggnnv4           3  0.0001              256   
41  0.80158         379     ggnnv4           3  0.0001              384   
45  0.79629         699     ggnnv4           4  0.0001              128   
54  0.80972         679     ggnnv4           4  0.0001              256   
62  0.81213         649     ggnnv4           4  0.0001              384   
66  0.74803         699     ggnnv4           5  0.0001              128   
74  0.79768         689     ggnnv4           5  0.0001              256   
82  0.79879         549     ggnnv4           5  0.0001              384   

    concat  city_pop_weight  data_word  data_category  data_city  data_pref  
8    False                0       True           True       True       True  
14   False                0       True           True       True       True  
21   False                0       True           True       True       True  
27   False                0       True           True       True       True  
34   False                0       True           True       True       True  
41   False                0       True           True       True       True  
45   False                0       True           True       True       True  
54   False                0       True           True       True       True  
62   False                0       True           True       True       True  
66   False                0       True           True       True       True  
74   False                0       True           True       True       True  
82   False                0       True           True       True       True

In [ ]:
df[df['model_type']==]