In [2]:
import torch 
a = torch.tensor([1,4,5])
a[torch.tensor([0,1,2,2,1,1,0,0])]

tensor([1, 4, 5, 5, 4, 4, 1, 1])

In [3]:
a = torch.rand(1,9)

In [5]:
a.reshape(-1)

tensor([0.8121, 0.5323, 0.1954, 0.6745, 0.4540, 0.9297, 0.5075, 0.5724, 0.3553])

In [6]:
d = {'a':1}
isinstance(d,dict)

True

In [12]:
a = torch.rand(3,2)
b = torch.rand(6,2)
a_size= a.size()[0]
b_size = b.size()[0]

In [13]:
c=torch.cat([a.repeat(1,b_size).view(a_size*b_size,-1), b.repeat(a_size, 1)],dim=1).view(a_size, b_size, 2*2)
c.size()

torch.Size([3, 6, 4])

In [16]:
import torch.nn as nn
attention = nn.Parameter(torch.zeros(size=(2*2, 1))) #xavier paramiter inizializator
nn.init.xavier_uniform_(attention.data, gain=1.414)
leakyReLU = nn.LeakyReLU(0.2)
attention = leakyReLU(torch.matmul(c, attention).squeeze(2))

In [17]:
attention

tensor([[-0.1523, -0.2347, -0.2393, -0.1633, -0.2116, -0.1812],
        [-0.2855, -0.3679, -0.3726, -0.2965, -0.3449, -0.3144],
        [-0.2330, -0.3154, -0.3200, -0.2440, -0.2923, -0.2619]],
       grad_fn=<LeakyReluBackward0>)

In [21]:
a = torch.rand(4,2)
b = torch.rand(4)
print(a)
print(b)
print(a*b.reshape(-1,1))

tensor([[0.8113, 0.1901],
        [0.6264, 0.0329],
        [0.3641, 0.6264],
        [0.0731, 0.3439]])
tensor([0.9536, 0.1569, 0.3461, 0.3377])
tensor([[0.7737, 0.1813],
        [0.0983, 0.0052],
        [0.1260, 0.2168],
        [0.0247, 0.1161]])


In [2]:
itenary = np.load('/home/yamanishi/project/trip_recommend/data/jalan/itenary_all.npy', allow_pickle=True)

In [4]:
len(itenary)

4907