In [5]:
from recommendation import get_data
data = get_data(category=True, city=True, prefecture=True)

In [6]:
data

HeteroData(
  (city, cityadj, city)=[2, 8445],
  spot={
    train_mask=[42852],
    valid_mask=[42852],
    test_mask=[42852],
    y=[42852],
    x=[42852, 512]
  },
  word={ x=[68340, 600] },
  category={ x=[290, 290] },
  city={
    x=[1709, 12],
    y=[1709],
    train_mask=[1709],
    valid_mask=[1709],
    test_mask=[1709]
  },
  pref={
    x=[47, 32],
    y=[47],
    train_mask=[47],
    valid_mask=[47],
    test_mask=[47]
  },
  user={
    x=[28251, 128],
    user_pos=[2146716],
    user_neg=[2146716],
    item_pos=[2146716],
    item_neg=[2146716]
  },
  (spot, relate, word)={ edge_index=[2, 642780] },
  (word, revrelate, spot)={ edge_index=[2, 642780] },
  (spot, has, category)={ edge_index=[2, 94658] },
  (category, revhas, spot)={ edge_index=[2, 94658] },
  (spot, belongs, city)={ edge_index=[2, 42852] },
  (city, revbelong, spot)={ edge_index=[2, 42852] },
  (pref, prefadj, pref)={ edge_index=[2, 172] },
  (city, belong, pref)={ edge_index=[2, 1991] },
  (pref, rebelong, ci

In [26]:
a = [torch.rand(2,3), torch.rand(2,3), torch.rand(2,3)]
print(a)
torch.stack(a, dim=1).size()
torch.mean(torch.stack(a, dim=1), dim=1)

[tensor([[0.2804, 0.7629, 0.5385],
        [0.6592, 0.8089, 0.4567]]), tensor([[0.6985, 0.2272, 0.7313],
        [0.3959, 0.5283, 0.0289]]), tensor([[0.4874, 0.2388, 0.7617],
        [0.7477, 0.3847, 0.7999]])]


tensor([[0.4888, 0.4096, 0.6771],
        [0.6009, 0.5740, 0.4285]])

In [12]:
df = pd.read_csv('/home/yamanishi/project/trip_recommend/model/recommendation/result/result.csv')
df.head()

recall  accuracy  best_epoch model_type  num_layers     lr  \
0  0.00172    0.0021           0        hgt           5  0.002   

   hidden_channels  concat  loss_city_weight  loss_category_weight  \
0               64   False                 0                     0   

   city_pop_weight  spot_pop_weight  data_word  data_category  data_city  \
0                0                0       True           True       True   

   data_prefecture  Unnamed: 16  
0             True     -0.74926

In [4]:
a = torch.rand(2,3)
b = torch.rand(2).unsqueeze(1)
print(a, b)
torch.div(a,b)

tensor([[0.0439, 0.9386, 0.7579],
        [0.7674, 0.6892, 0.6817]]) tensor([[0.1704],
        [0.9987]])


tensor([[0.2576, 5.5075, 4.4471],
        [0.7685, 0.6901, 0.6826]])

In [ ]:
e=torch.nn.Embedding(num_embeddings=10, embedding_dim=5)
e.shape

Embedding(10, 5)

In [ ]:
a,b = torch.unique([1,2,1,2,3,3,1], return_counts=True)
zero = torch.zeros(4)
zero[a]=b

In [6]:
from torch_geometric.nn.conv import HANConv, HGTConv
conv = HANConv(in_channels=-1, out_channels=128, metadata=data.metadata())
conv = HGTConv(in_channels=-1, out_channels=128, metadata=data.metadata(), heads=4, group='mean')

In [15]:
device = 'cuda:0'
data.to(device)
conv.to(device)
conv(data.x_dict, data.edge_index_dict)

{'spot': tensor([[-0.0288, -0.0596,  0.0634,  ...,  0.0194,  0.0320,  0.0303],
         [-0.0655, -0.0652,  0.0009,  ...,  0.0245,  0.0261,  0.0752],
         [ 0.0032, -0.0506,  0.0455,  ..., -0.0364, -0.0711,  0.0404],
         ...,
         [-0.0679, -0.0551,  0.0629,  ..., -0.0462,  0.0336,  0.0534],
         [-0.0356, -0.0256,  0.0379,  ..., -0.0378,  0.0169,  0.0432],
         [-0.0527, -0.0557,  0.0059,  ..., -0.0278,  0.0228, -0.0088]],
        device='cuda:0', grad_fn=<AddmmBackward0>),
 'word': tensor([[-1.9727e-01,  9.5084e-04, -3.6135e-03,  ...,  8.4128e-03,
           1.4423e-01,  1.6481e-01],
         [-4.8239e-01,  3.6992e-01, -1.3637e-01,  ..., -4.3266e-01,
           5.1114e-01,  4.1980e-01],
         [-6.1266e-02,  2.3281e-01,  2.4414e-01,  ..., -1.4070e-01,
           2.7913e-01,  2.4021e-01],
         ...,
         [-1.5504e-01,  1.2582e-01,  3.5365e-02,  ...,  3.5207e-02,
           1.3466e-01,  9.7789e-02],
         [-3.3779e-01,  1.4885e-01,  3.5253e-04,  ..., -1

In [1]:
str(True)

'True'

In [4]:
data

HeteroData(
  spot={
    train_mask=[42852],
    valid_mask=[42852],
    test_mask=[42852],
    y=[42852],
    x=[42852, 512]
  },
  word={ x=[68340, 600] },
  user={
    x=[28251, 128],
    user_pos=[2146716],
    user_neg=[2146716],
    item_pos=[2146716],
    item_neg=[2146716]
  },
  (spot, relate, word)={ edge_index=[2, 642780] },
  (word, revrelate, spot)={ edge_index=[2, 642780] },
  (user, visit, spot)={ edge_index=[2, 2146716] },
  (spot, revvisit, user)={ edge_index=[2, 2146716] }
)

In [5]:
from torch_geometric.nn import HeteroLinear
linear = HeteroLinear(-1, 128, len(data.x_dict.keys()))
linear(data.x_dict)

TypeError: forward() missing 1 required positional argument: 'type_vec'

In [1]:
import torch.nn as nn
encoder_layer = nn.TransformerEncoderLayer(d_model=512, nhead=8)
transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=6)
src = torch.rand(10, 32, 512)
out = transformer_encoder(src)

In [3]:
transformer_encoder(torch.rand(500,5,512))

tensor([[[ 1.6938, -0.4604,  1.3951,  ..., -0.4941, -0.1565,  0.1207],
         [-0.3422, -0.8063,  1.7492,  ..., -1.3343,  0.0558, -0.4790],
         [-0.4813, -0.8356,  1.6242,  ..., -1.1597, -0.1464,  0.4727],
         [-1.4184, -0.7773,  1.1830,  ..., -0.4891, -0.2813,  0.2164],
         [ 0.0397, -1.0320,  2.3576,  ..., -0.6497, -0.9610, -0.2784]],

        [[ 0.4420, -0.3877,  1.7163,  ..., -0.1106, -0.7346,  0.9244],
         [-0.1781, -0.4102,  1.5294,  ...,  0.1275,  0.0566,  0.1262],
         [-0.6370,  0.1568,  1.3207,  ..., -0.6263,  0.0112,  0.0030],
         [-0.0536, -0.5924,  0.6969,  ...,  0.0097,  0.2753,  0.1213],
         [ 0.1633, -0.7276,  0.8970,  ..., -1.2248,  0.3632,  0.3481]],

        [[ 0.3711, -1.0998,  0.9549,  ..., -1.2546, -0.4199, -0.5805],
         [-0.1377, -0.2571,  2.1186,  ..., -1.5979,  0.2015,  0.6335],
         [-0.5531, -0.0821,  1.8383,  ..., -0.7377, -0.6298, -0.5093],
         [-0.7340, -0.2288,  1.8524,  ..., -1.0687,  0.0162, -0.3630],
  

In [1]:
import os
 
isempty = os.stat('/home/yamanishi/project/trip_recommend/model/recommendation/result.csv').st_size == 0
print(isempty)

True


In [3]:
a = 0.224151533535
round(a,5)

0.22415

In [4]:
a=np.array(['a','b','c'])
with open('log.txt', 'w') as f:
    f.write('train','max', a.)

TypeError: write() takes exactly one argument (3 given)

In [8]:
import torch.nn as nn
gru = nn.GRUCell(128,128)

In [10]:
gru(torch.rand(512,128), torch.rand(512,128)).shape

torch.Size([512, 128])

In [3]:
a = torch.rand(3,2)
print(a)
print(a.norm(2))
a.norm(2).pow(2)

tensor([[0.0282, 0.8086],
        [0.4328, 0.8383],
        [0.5413, 0.9000]])
tensor(1.6272)


tensor(2.6476)